# Generated by Django 4.1.2 on 2022-11-01 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sotrudnik",
                    models.CharField(
                        choices=[
                            ("", "Выберите категорию обращения"),
                            ("Замена Картриджа", "Замена Картриджа"),
                            (
                                "Устранение неполадок с техникой",
                                "Устранение неполадок с техникой",
                            ),
                            ("Выдача оборудования", "Выдача оборудования"),
                            ("Другое", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории",},
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "adress",
                    models.CharField(
                        choices=[
                            ("", "Выберите корпус"),
                            ("ШО1", "ШО1"),
                            ("ШО2", "ШО2"),
                            ("ШО8", "ШО8"),
                            ("ШО16", "ШО16"),
                        ],
                        max_length=4,
                        verbose_name="Корпус",
                    ),
                ),
                ("kabinet", models.IntegerField(verbose_name="Введите кабинет")),
                ("task", models.TextField(verbose_name="Описание")),
                (
                    "sotrudnik",
                    models.CharField(
                        choices=[
                            ("", "Выберите сотрудника"),
                            ("AA", "Артем Андреевич"),
                            ("YI", "Ярослав Игоревич"),
                            ("SV", "Сергей Викторович"),
                            ("NO", "Никита Олегович"),
                        ],
                        max_length=2,
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "kat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.kategoria"
                    ),
                ),
            ],
            options={"verbose_name": "Заявка", "verbose_name_plural": "Заявки",},
        ),
    ]
