# Generated by Django 4.1.2 on 2022-10-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "adress",
                    models.CharField(
                        choices=[
                            ("", "Выберите корпус"),
                            ("ШО1", "ШО1"),
                            ("ШО2", "ШО2"),
                            ("ШО8", "ШО8"),
                            ("ШО16", "ШО16"),
                        ],
                        max_length=4,
                        verbose_name="Корпус",
                    ),
                ),
                ("kabinet", models.IntegerField(verbose_name="Введите кабинет")),
                ("task", models.TextField(verbose_name="Описание")),
                (
                    "sotrudnik",
                    models.CharField(
                        choices=[
                            ("", "Выберите сотрудника"),
                            ("AA", "Артем Андреевич"),
                            ("YI", "Ярослав Игоревич"),
                            ("SV", "Сергей Викторович"),
                            ("NO", "Никита Олегович"),
                        ],
                        max_length=2,
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={"verbose_name": "Заявка", "verbose_name_plural": "Заявки",},
        ),
    ]
