# Generated by Django 4.1.2 on 2022-10-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "adress",
                    models.CharField(
                        choices=[
                            ("1", "ШО1"),
                            ("2", "ШО2"),
                            ("8", "ШО8"),
                            ("16", "ШО16"),
                        ],
                        max_length=3,
                        verbose_name="Корпус",
                    ),
                ),
                ("task", models.TextField(verbose_name="Описание")),
            ],
        ),
    ]
