# Generated by Django 4.1.2 on 2022-10-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="adress",
            field=models.CharField(
                choices=[
                    ("", "Выберите корпус"),
                    ("ШО1", "ШО1"),
                    ("ШО2", "ШО2"),
                    ("ШО8", "ШО8"),
                    ("ШО16", "ШО16"),
                ],
                max_length=4,
                verbose_name="Корпус",
            ),
        ),
    ]
