# Generated by Django 4.1.2 on 2022-10-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Заявка", "verbose_name_plural": "Заявки"},
        ),
        migrations.AlterField(
            model_name="task",
            name="adress",
            field=models.CharField(
                choices=[
                    ("ШО1", "ШО1"),
                    ("ЩО2", "ШО2"),
                    ("ШО8", "ШО8"),
                    ("ШО16", "ШО16"),
                ],
                max_length=4,
                verbose_name="Корпус",
            ),
        ),
    ]
