# Generated by Django 4.1.2 on 2022-11-01 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_task_kat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kategoria", old_name="sotrudnik", new_name="kategoria",
        ),
        migrations.AlterField(
            model_name="task",
            name="kat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main.kategoria"
            ),
        ),
    ]
