# Generated by Django 4.1.2 on 2022-11-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_task_kat"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="title",),
    ]
