# Generated by Django 4.1.2 on 2022-11-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_remove_task_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kategoria",
            name="kategoria",
            field=models.CharField(
                choices=[
                    ("", "Выберите категорию обращения"),
                    ("", "Выберите категорию"),
                    ("Замена Картриджа", "Замена Картриджа"),
                    (
                        "Устранение неполадок с техникой",
                        "Устранение неполадок с техникой",
                    ),
                    ("Выдача оборудования", "Выдача оборудования"),
                    ("Другое", "Другое"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="Категория",
            ),
        ),
    ]
