# Generated by Django 4.1.2 on 2022-11-02 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_kategoria_kategoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="kat",
            field=models.ForeignKey(
                choices=[
                    ("", "Выберите категорию"),
                    ("Замена Картриджа", "Замена Картриджа"),
                    (
                        "Устранение неполадок с техникой",
                        "Устранение неполадок с техникой",
                    ),
                    ("Выдача оборудования", "Выдача оборудования"),
                    ("Другое", "Другое"),
                ],
                on_delete=django.db.models.deletion.PROTECT,
                to="main.kategoria",
            ),
        ),
    ]
