# Generated by Django 4.1.2 on 2022-11-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_kategoria_kategoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="kat_s",
            field=models.CharField(
                choices=[
                    ("", "Выберите категорию"),
                    ("Замена Картриджа", "Замена Картриджа"),
                    (
                        "Устранение неполадок с техникой",
                        "Устранение неполадок с техникой",
                    ),
                    ("Выдача оборудования", "Выдача оборудования"),
                    ("Другое", "Другое"),
                ],
                default="e",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="kat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main.kategoria"
            ),
        ),
    ]
