# Generated by Django 4.1.2 on 2022-11-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_task_kat_s_alter_task_kat"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="kat_s",),
    ]
